import base64

# Standard 1080p EDID (base64 encoded)
edid_b64 = "AP///////wAGEHycAAAAAAABAQSBAHGAPwAAoFclQjMATUEAAAABAQEBAQEBAQEBAQEBAQEBAAAAABAAAAAA/wBAAAAYAAAAAAAAAAAAAAAAMAAAAAAA/wBAAAAYAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

with open("1080p_edid.bin", "wb") as f:
    f.write(base64.b64decode(edid_b64))

print("1080p_edid.bin generated.")
